version: "3"

services:
  albyhub:
    image: ghcr.io/getalby/hub:latest
    container_name: alby_hub
    ports:
      - "8080:8080"
    volumes:
      - ./data:/data
    environment:
      - WORK_DIR=/data
    command: ["./entrypoint.sh"]  # Change this based on your application's actual start command
